project/impl/src/Entity/Goal.php
<?php

namespace App\Entity;

use App\Repository\GoalRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GoalRepository::class)]
class Goal
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $start_date = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $end_date = null;

    #[ORM\Column(nullable: true)]
    private ?int $target_cards = null;

    #[ORM\Column(nullable: true)]
    private ?int $achieved_cards = null;

    #[ORM\Column(nullable: true)]
    private ?int $target_tests = null;

    #[ORM\Column(nullable: true)]
    private ?int $achieved_tests = null;

    #[ORM\Column]
    private ?bool $completed = false;

    #[ORM\Column]
    private ?bool $bonus_granted = false;

    #[ORM\ManyToOne(inversedBy: 'goals')]
    #[ORM\JoinColumn(nullable: false)]
    private ?AppUser $owner = null;

    #[ORM\Column]
    private ?bool $is_current = false;

    // Return identifier
    public function getId(): ?int
    {
        return $this->id;
    }

    // Return time when goal was started
    public function getStartDate(): ?\DateTimeImmutable
    {
        return $this->start_date;
    }

    // Sets time when goal would be started
    public function setStartDate(\DateTimeImmutable $start_date): static
    {
        $this->start_date = $start_date;

        return $this;
    }

    // Return time when goal would be ended
    public function getEndDate(): ?\DateTimeImmutable
    {
        return $this->end_date;
    }

    // Sets time when goal would be ended
    public function setEndDate(\DateTimeImmutable $end_date): static
    {
        $this->end_date = $end_date;

        return $this;
    }

    // Get count of target cards to study if exists
    public function getTargetCards(): ?int
    {
        return $this->target_cards;
    }

    // Sets count of target cards to study
    public function setTargetCards(?int $target_cards): static
    {
        $this->target_cards = $target_cards;

        return $this;
    }

    // Return achieved cards if exists
    public function getAchievedCards(): ?int
    {
        return $this->achieved_cards;
    }

    // Sets achieved cards
    public function setAchievedCards(?int $achieved_cards): static
    {
        $this->achieved_cards = $achieved_cards;

        return $this;
    }

    // Get count of target tests to finish if exists
    public function getTargetTests(): ?int
    {
        return $this->target_tests;
    }

    // Sets count of target tests to finish
    public function setTargetTests(?int $target_tests): static
    {
        $this->target_tests = $target_tests;

        return $this;
    }

    // Return achieved tests if exists
    public function getAchievedTests(): ?int
    {
        return $this->achieved_tests;
    }

    // Sets achieved tests
    public function setAchievedTests(?int $achieved_tests): static
    {
        $this->achieved_tests = $achieved_tests;

        return $this;
    }

    // Check if goal is completed
    public function isCompleted(): ?bool
    {
        return $this->completed;
    }

    // Sets completion of goal
    public function setCompleted(bool $completed): static
    {
        $this->completed = $completed;

        return $this;
    }

    // Check if bonus was granted
    public function isBonusGranted(): ?bool
    {
        return $this->bonus_granted;
    }

    // Sets if bonus was granted
    public function setBonusGranted(bool $bonus_granted): static
    {
        $this->bonus_granted = $bonus_granted;

        return $this;
    }

    // Return goal's owner
    public function getOwner(): ?AppUser
    {
        return $this->owner;
    }

    // Sets owner to goal
    public function setOwner(?AppUser $owner): static
    {
        $this->owner = $owner;

        return $this;
    }

    // Increase achieved cards and check if goal is completed
    public function increaseAchievedCards(): static{
        $this->achieved_cards++;
        if ($this->achieved_cards >= $this->target_cards){
            if ($this->target_tests && $this->achieved_tests >= $this->target_tests)
                $this->completed = true;
            else if (! $this->target_tests)
                $this->completed = true;
        }
        return $this;
    }

    // Increase achieved tests and check if goal is completed
    public function increaseAchievedTests(): static{
        $this->achieved_tests++;
        if ($this->achieved_tests >= $this->target_tests){
            if ($this->target_cards && $this->achieved_cards >= $this->target_cards)
                $this->completed = true;
            else if (! $this->target_cards)
                $this->completed = true;
        }
        return $this;
    }

    // Check if goal is current
    public function isCurrent(): ?bool
    {
        return $this->is_current;
    }

    // Sets if goal is current
    public function setIsCurrent(bool $is_current): static
    {
        $this->is_current = $is_current;

        return $this;
    }
}

project/impl/src/Entity/Notification.php
<?php

namespace App\Entity;

use App\Repository\NotificationRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints;

#[ORM\Entity(repositoryClass: NotificationRepository::class)]
class Notification
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Constraints\Length(min: 1, max: 255)]
    private ?string $message = null;

    #[ORM\Column]
    private ?bool $is_read = false;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\ManyToOne(inversedBy: 'notifications')]
    #[ORM\JoinColumn(nullable: false)]
    private ?AppUser $person_to_notificate = null;

    // Returns identifier
    public function getId(): ?int
    {
        return $this->id;
    }

    // Return message of the notification
    public function getMessage(): ?string
    {
        return $this->message;
    }

    // Sets message to notification
    public function setMessage(string $message): static
    {
        $this->message = $message;

        return $this;
    }

    // Check if notification was read
    public function isRead(): ?bool
    {
        return $this->is_read;
    }

    // Sets if notification was read
    public function setIsRead(bool $is_read): static
    {
        $this->is_read = $is_read;

        return $this;
    }

    // Return time when notification was created
    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    // Sets time when notification was created
    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    // Return person who is notificated
    public function getPersonToNotificate(): ?AppUser
    {
        return $this->person_to_notificate;
    }

    // Sets person to notificate
    public function setPersonToNotificate(?AppUser $person_to_notificate): static
    {
        $this->person_to_notificate = $person_to_notificate;

        return $this;
    }
}

project/impl/src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\AppUser;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email', EmailType::class, [
                'label'=>'E-mail',
                'required' => false,
                'mapped' => false,
            ])
            ->add('login', TextType::class, [
                'label' => 'Login',
                'required' => false,
                'mapped' => false,
            ])
            ->add('password', PasswordType::class, [
                'label' => 'Heslo',
                'required' => false,
                'mapped' => false,
            ])
            ->add('new_verification', CheckboxType::class, [
                'label' => 'Znovu odeslat potvrzovací e-mail',
                'required' => false,
                'mapped' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([]);
    }
}

project/impl/src/Controller/Api/UserController.php
<?php
declare(strict_types=1);

/* This file contains code adapted from the Symfony documentation:
   - Serializer component://symfony.com/doc/current/serializer/.html#deserializing-an-object
   - Validator component: https://symfony.com/doc/current/validation.html
   Used for deserializing JSON data into an object and validating it.
*/

namespace App\Controller\Api;

use App\Entity\Goal;
use App\Entity\AppUser;
use App\Factory\GoalFactory;
use App\Service\UserService;
use App\Resource\CollectionResource;
use App\Resource\GoalResource;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\Validator\Validator\ValidatorInterface;

#[Route(path: '/api/user')]
#[IsGranted('IS_AUTHENTICATED_FULLY')]
class UserController extends AbstractController
{
    public function __construct(
        private UserService $userService,
        private GoalFactory $goalFactory
    ) {}

    // Returns a JSON response with the user's goals.
    #[Route('/goals', name: 'api_goals', methods: ['GET'])]
    public function goals():Response{
        /** @var AppUser $user */
        $user = $this->getUser();
        $goals = $user->getGoals();
        return $this->json(new CollectionResource(
            _self: $this->generateUrl('api_goals'),
            data: array_map(fn(Goal $goal) => $this->goalFactory->list($goal),
            $goals->toArray())
        ));
    }

    /* Handles creating a new goal for the user if they don't have an existing one.
       Deserializes the request content into a GoalResource object, validates the goal,
       and stores it. Returns the details of the created goal in a JSON response. */
    #[Route('/goals', name: 'api_new_goal', methods: ['POST'])]
    public function new_goal(Request $request, SerializerInterface $serializer, ValidatorInterface $validator): Response{
        /** @var AppUser $user */
        $user = $this->getUser();
        if ($user->getActualGoal())
            throw new \LogicException('Cíl na tento týden již byl nastaven');
        $resource = $serializer->deserialize(
            $request->getContent(),
            GoalResource::class,
            'json'
        );
        $goal = new Goal();
        $this->goalFactory->create($resource, $goal);
        if (
            ($goal->getTargetCards() === null || $goal->getTargetCards() <= 0) &&
            ($goal->getTargetTests() === null || $goal->getTargetTests() <= 0)
        ) {
            return $this->json(['error' => 'Musíte zadat alespoň jeden cíl větší než 0'], 400);
        }
        $violations = $validator->validate($goal);
        if (count($violations) > 0) {
            return $this->json((string) $violations, 400);
        }
        $this->userService->setGoal($user, $goal);
        return $this->json($this->goalFactory->list($goal));
    }
}

project/impl/src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Goal;
use App\Entity\Notification;
use App\Form\GoalType;
use App\Form\UserType;
use App\Entity\AppUser;
use App\Service\UserService;
use App\Repository\NotificationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/user')]
#[IsGranted('IS_AUTHENTICATED_FULLY')]
class UserController extends AbstractController
{

    public function __construct(
        private UserService            $userService,
        private NotificationRepository $notificationRepository
    ) {}

    /* Displays and processes the user profile settings form.
       Handles the user settings form. If the form is valid and submitted, updates the user's data. */
    #[Route('/', name: 'app_user')]
    public function index(Request $request, UserPasswordHasherInterface $passwordHasher): Response
    {
        /** @var AppUser $user */
        $user = $this->getUser();
        $unread_notifications = $this->notificationRepository->countUnreadForUser($user);
        $form = $this->createForm(UserType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $this->userService->edit($user, $form, $passwordHasher);
        }
        return $this->render('user/index.html.twig', [
            'form' => $form,
            'unread_notifications' => $unread_notifications
        ]);
    }

    // Displays the user's current and previous goals.
    #[Route('/goals', name: 'goals')]
    public function goals():Response{
        /** @var AppUser $user */
        $user = $this->getUser();
        $actual_goal = $user->getActualGoal();
        $previous_goals = $user->getPreviousGoals();
        $unread_notifications = $this->notificationRepository->countUnreadForUser($user);
        return $this->render('user/goals.html.twig', [
            'actual_goal' => $actual_goal,
            'previous_goals' => $previous_goals,
            'unread_notifications' => $unread_notifications
        ]);
    }

    /* Creates a new goal for the user if they don't have an existing one.
       If the goal is valid, it sets the goal and redirects to the goals page. */
    #[Route('/new_goal', name: 'new_goal')]
    public function new_goal(Request $request): Response{
        /** @var AppUser $user */
        $user = $this->getUser();
        if ($user->getActualGoal())
            throw new \LogicException('Cíl na tento týden již byl nastaven');
        $goal = new Goal();
        $form = $this->createForm(GoalType::class, $goal);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            if (($goal->getTargetCards() ?? 0) <= 0 &&
                ($goal->getTargetTests() ?? 0) <= 0
            ) {
                $form->addError(new FormError('Musíte zadat alespoň jeden cíl větší než 0'));
            }
            else {
                $this->userService->setGoal($user, $goal);
                return $this->redirectToRoute('goals');
            }
        }
        return $this->render('user/new_goal.html.twig', [
            'form' => $form
        ]);
    }

    // Check if goal is completed. Displays a page indicating the user has completed their goal for the week.
    #[Route('/completed_goal', name: 'completed_goal')]
    public function competed_goal(): Response{
        /** @var AppUser $user */
        $user = $this->getUser();
        $actual_goal = $user->getActualGoal();
        if (!$actual_goal)
            throw new \LogicException('Cíl na tento týden ještě nebyl nastavěn');
        if (!$actual_goal->isCompleted())
            throw new \LogicException('Cíl na tento týden ještě nebyl splněn');
        $this->userService->completeGoal($actual_goal);
        return $this->render('user/completed_goal.html.twig', [
            'actual_goal' => $actual_goal
        ]);
    }

    // Display user's notifications.
    #[Route('/notifications', name: 'notifications')]
    public function show_notifications(): Response{
        /** @var AppUser $user */
        $user = $this->getUser();
        $notifications = $user->getNotifications();
        return $this->render('user/notifications.html.twig', [
            'notifications' => $notifications
        ]);
    }

    // Marks a notification as read for the current user.
    #[Route('/notifications/{id}/read', name: 'read_notification', requirements: ['id' => '\d+'])]
    public function read_notification(Notification $notification): Response{
        /** @var AppUser $user */
        $user = $this->getUser();
        if ($notification->getPersonToNotificate() !== $user)
            throw $this->createAccessDeniedException();
        $this->userService->readNotification($notification);
        return $this->redirectToRoute('notifications');
    }
}

project/impl/templates/user/completed_goal.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="{{ asset('/styles/completed_goal.css') }}">
{% endblock %}

{% block header %}
    <h1>Gratulujeme!🎉</h1>
{% endblock %}

{% block content %}
    <section class="content">
        <h2>Splnili jste cíl na tento týden</h2>
        {% if actual_goal.targetCards %}
            <p>Prostudoval jste {{ actual_goal.achievedCards }} kartiček</p>
            <p>Za to získáváte bonus – den pauzy v učení.</p>
            <div class="bonus" title="Bonus: možnost přeskočit jeden den bez ztráty pokroku">
                <i class="fa-solid fa-calendar-xmark"></i>
            </div>
        {% endif %}
        {% if actual_goal.targetTests %}
            <p>Úspěšně jste dokončil {{ actual_goal.achievedTests }} testů</p>
            <p>Za to získáváte bonus – možnost považovat neúspěšný test za úspěšný pro příští cíl</p>
            <div class="bonus" title="Bonus: možnost započítat si neúspěšný test jako úspěšný">
                <i class="fa-solid fa-handshake"></i>
            </div>
        {% endif %}
        <a href="{{ path('goals') }}">Nastavit nový cíl</a>
    </section>
{% endblock %}

project/impl/templates/user/goals.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="{{ asset('/styles/goals.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('/styles/modal.css') }}">
{% endblock %}

{% block scripts %}
    <script type="module" src="{{ asset('/scripts/modalInicialize.js') }}" defer></script>
{% endblock %}

{% block content %}
    <section class="menu">
        <a href="{{ path('decks') }}">Kolekce</a>
        <a href="{{ path('my_decks') }}">Moje kolekce</a>
        <a href="{{ path('stats') }}">Statistiky</a>
        <a href="{{ path('app_user') }}">Nastaveni</a>
        <div class="bottom_links">
            <a href="{{ path('notifications') }}" title="Notifikace"
               {% if unread_notifications > 0 %}class="unread"{% endif %}>
                <i class="fa-solid fa-bell"></i>
            </a>
            <a href="{{ path('logout') }}" title="Odhlásit se"><i class="fa-solid fa-right-from-bracket"></i></a>
        </div>
    </section>
    <section class="goals">
        <h2>Moje cíle</h2>
        <div class="actual_goal">
            <h3>Aktuální cíl</h3>
            {% if actual_goal %}
                {% if actual_goal.targetCards %}
                    <p>Prostudovat {{ actual_goal.targetCards }} kartiček</p>
                    <div class="progress_container" title="Počet prostudovaných kartiček za týden">
                        <div class="progress_bar" style="width:
                        {% if actual_goal.achievedCards >= actual_goal.targetCards  %}100{% else %}{{100*actual_goal.achievedCards/actual_goal.targetCards}}{% endif %}%;">
                            {% if actual_goal.achievedCards > 0 %}
                                {{ actual_goal.achievedCards }}
                            {% endif %}
                        </div>
                    </div>
                {% endif %}
                {% if actual_goal.targetTests %}
                    <p>Úspěšně dokončit {{ actual_goal.targetTests }} testů</p>
                    <p>Za úspěšný se považuje test, pokud je správně zodpovězeno alespoň tři čtvrtiny otázek </p>
                    <div class="progress_container" title="Počet dokončených testů za týden">
                        <div class="progress_bar" style="width:
                        {% if actual_goal.achievedTests >= actual_goal.targetTests  %}100{% else %}{{100*actual_goal.achievedTests/actual_goal.targetTests}}{% endif %}%;">
                            {% if actual_goal.achievedTests > 0 %}
                                {{ actual_goal.achievedTests }}
                            {% endif %}
                        </div>
                    </div>
                {% endif %}
                <p>Do: <time datetime="{{ actual_goal.endDate|date('Y-m-d') }}">{{ actual_goal.endDate|date('d.m.Y') }}</time></p>
            {% else %}
               <p>Nemáte nastavený cíl na tento týden</p>
                <a id="openModal"
                   data-value="create_goal"
                   href="{{ path('new_goal') }}"
                   data-url="{{ path('api_new_goal') }}">
                    Nastavit</a>
            {% endif %}
        </div>
        <div class="goals_info">
            <p>Cíle jsou nastaveny na týden, ale můžete je dokončit i dříve, pokud je splníte v kratším čase.</p>
            <p>Za splnění cílů získáte odměny</p>
            <ul>
                <li>Za naučené kartičky získáte možnost přeskočit jeden den bez ztráty pokroku</li>
                <li>Za úspěšně dokončený test (úspěšný je ten, u kterého odpovíte správně alespoň na tři čtvrtiny otázek) získáte možnost započítat si neúspěšný test jako úspěšný</li>
            </ul>
        </div>
        {% if previous_goals is not empty %}
        <div class="previous_goals">
            <h3>Předchozí cíle</h3>
            {% for goal in previous_goals %}
                <div class="goal">
                    {% if goal.targetCards %}
                        <div class="cards">
                            <p>Prostudovat {{ goal.targetCards }} kartiček</p>
                            <div class="progress_container" title="Počet prostudovaných kartiček za týden">
                                <div class="progress_bar" style="width: {% if goal.achievedCards >= goal.targetCards  %}100{% else %}{{100*goal.achievedCards/goal.targetCards}}{% endif %}%;">
                                    {% if goal.achievedCards > 0 %}
                                        {{ goal.achievedCards }}
                                    {% endif %}
                                </div>
                            </div>
                            {% if goal.bonusGranted %}
                                <div class="bonus" title="Bonus: možnost přeskočit jeden den bez ztráty pokroku">
                                    <i class="fa-solid fa-calendar-xmark"></i>
                                </div>
                            {% endif %}
                        </div>
                    {% endif %}
                    {% if goal.targetTests %}
                        <div class="tests">
                            <p>Úspěšně dokončit {{ goal.targetTests }} testů</p>
                            <div class="progress_container" title="Počet dokončených testů za týden">
                                <div class="progress_bar" style="width: {% if goal.achievedTests >= goal.targetTests  %}100{% else %}{{100*goal.achievedTests/goal.targetTests}}{% endif %}%;">
                                    {% if goal.achievedTests > 0 %}
                                        {{ goal.achievedTests }}
                                    {% endif %}
                                </div>
                            </div>
                            {% if goal.bonusGranted %}
                                <div class="bonus" title="Bonus: možnost započítat si neúspěšný test jako úspěšný">
                                    <i class="fa-solid fa-handshake"></i>
                                </div>
                            {% endif %}
                        </div>
                    {% endif %}
                    <div class="time">
                        <p>Od: <time datetime="{{ goal.startDate|date('Y-m-d') }}">{{ goal.startDate|date('d.m.Y') }}</time></p>
                        <p>{% if goal.completed %}Splněno{% else %}Do{% endif %}: <time datetime="{{ goal.endDate|date('Y-m-d') }}">{{ goal.endDate|date('d.m.Y') }}</time></p>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% endif %}
    </section>
    <dialog id="dialog">
        <button id="closeModal">❌</button>
    </dialog>
{% endblock %}

project/impl/templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="{{ asset('/styles/user.css') }}">
{% endblock %}

{% block content %}
    <section class="menu">
        <a href="{{ path('decks') }}">Kolekce</a>
        <a href="{{ path('my_decks') }}">Moje kolekce</a>
        <a href="{{ path('stats') }}">Statistiky</a>
        <a href="{{ path('goals') }}">Moje cíle</a>
        <div class="bottom_links">
            <a href="{{ path('notifications') }}" title="Notifikace"
               {% if unread_notifications > 0 %}class="unread"{% endif %}>
                <i class="fa-solid fa-bell"></i>
            </a>
            <a href="{{ path('logout') }}" title="Odhlásit se"><i class="fa-solid fa-right-from-bracket"></i></a>
        </div>
    </section>
    <section class="users_info">
        <h2>Upravit informace profilu</h2>
        {{ form_start(form) }}
        {{ form_errors(form) }}
        {{ form_rest(form) }}
        <button type="submit">Uložit</button>
        {{ form_end(form) }}
    </section>
{% endblock %}

project/impl/templates/user/new_goal.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="{{ asset('/styles/form.css') }}">
{% endblock %}

{% block header %}
    <div class="head">
        <h1>Nová cíl</h1>
        <p><a href="{{ path('goals') }}">Zpět</a></p>
    </div>
{% endblock %}

{% block content %}
    <section class="form">
        {{ form_start(form) }}
        {{ form_errors(form) }}
        {{ form_rest(form) }}
        <button type="submit">Nastavit</button>
        {{ form_end(form) }}
    </section>
{% endblock %}

project/impl/templates/user/notifications.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="{{ asset('/styles/notifications.css') }}">
{% endblock %}

{% block header %}
    <div class="head">
        <h1>Notifikace</h1>
        <p><a href="{{ path('my_decks') }}">Zpět</a></p>
    </div>
{% endblock %}

{% block content %}
    <section class="content">
        <div class="notifications">
            {% if notifications is not empty %}
                {% for notif in notifications|sort((a, b) => b.createdAt <=> a.createdAt) %}
                    <div class="notification {% if not notif.isRead %} not_read{% endif %}">
                        <p>{{ notif.message }}</p>
                        <p><time datetime="{{ notif.createdAt|date('Y-m-d') }}">{{ notif.createdAt|date('d.m.Y') }}</time></p>
                        <a href="{{ path('read_notification', {id: notif.id}) }}"></a>
                    </div>
                {% endfor %}
            {% else %}
                <p>Žádné nové oznámení</p>
            {% endif %}
        </div>
    </section>
{% endblock %}