project/impl/src/Entity/Card.php
<?php

namespace App\Entity;

use App\Repository\CardRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CardRepository::class)]
class Card
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $front_side = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $back_side = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $to_learn = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $last_learned = null;

    #[ORM\Column(nullable: true)]
    private ?int $learn_score = null;

    #[ORM\ManyToOne(inversedBy: 'cards')]
    private ?Deck $deck = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $front_image = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $back_image = null;

    #[ORM\OneToMany(targetEntity: TestResult::class, mappedBy: 'card')]
    private Collection $testResults;

    public function __construct()
    {
        $this->testResults = new ArrayCollection();
    }

    // Return identifier
    public function getId(): ?int
    {
        return $this->id;
    }

    // Return text from the front side of card
    public function getFrontSide(): string
    {
        return $this->front_side;
    }

    // Sets text to front side of card
    public function setFrontSide(string $front_side): static
    {
        $this->front_side = $front_side;

        return $this;
    }

    // Return text from the back side of card
    public function getBackSide(): string
    {
        return $this->back_side;
    }

    // Sets text to back side of card
    public function setBackSide(string $back_side): static
    {
        $this->back_side = $back_side;

        return $this;
    }

    // Return time when card must be learned
    public function getToLearn(): ?\DateTimeInterface
    {
        return $this->to_learn;
    }

    // Sets time when card must be learned
    public function setToLearn(?\DateTimeInterface $to_learn): static
    {
        $this->to_learn = $to_learn;

        return $this;
    }

    // Return time when card was learned for the last time
    public function getLastLearned(): ?\DateTimeImmutable
    {
        return $this->last_learned;
    }

    // Sets time when card was learned for the last time
    public function setLastLearned(?\DateTimeImmutable $last_learned): void
    {
        $this->last_learned = $last_learned;
    }

    // Return score for last learning of card
    public function getLearnScore(): ?int
    {
        return $this->learn_score;
    }

    // Sets score for last learning of card
    public function setLearnScore(?int $learn_score): static
    {
        $this->learn_score = $learn_score;

        return $this;
    }

    // Return deck that the card belongs to
    public function getDeck(): ?Deck
    {
        return $this->deck;
    }

    // Sets deck that the card belongs to
    public function setDeck(?Deck $deck): static
    {
        $this->deck = $deck;

        return $this;
    }

    // Get image on the front side of card if exists
    public function getFrontImage(): ?string
    {
        return $this->front_image;
    }

    // Sets image to the front side of card
    public function setFrontImage(?string $front_image): static
    {
        $this->front_image = $front_image;

        return $this;
    }

    // Get image on the back side of card if exists
    public function getBackImage(): ?string
    {
        return $this->back_image;
    }

    // Sets image to the back side of card
    public function setBackImage(?string $back_image): static
    {
        $this->back_image = $back_image;

        return $this;
    }

    // Return questions that are associated with card
    /**
     * @return Collection<int, TestResult>
     */
    public function getTestResults(): Collection
    {
        return $this->testResults;
    }

    // Add question that is associated with card
    public function addTestResult(TestResult $testResult): static
    {
        if (!$this->testResults->contains($testResult)) {
            $this->testResults->add($testResult);
            $testResult->setCard($this);
        }

        return $this;
    }

    // Remove question associated with card
    public function removeTestResult(TestResult $testResult): static
    {
        if ($this->testResults->removeElement($testResult)) {
            if ($testResult->getCard() === $this) {
                $testResult->setCard(null);
            }
        }

        return $this;
    }

    // Checks if card can be studied now
    public function canStudyNow(): bool{
        if ($this->last_learned){
            return $this->to_learn <= new \DateTimeImmutable();
        }
        return true;
    }
}

project/impl/src/Entity/Review.php
<?php

namespace App\Entity;

use App\Repository\ReviewRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints;

#[ORM\Entity(repositoryClass: ReviewRepository::class)]
class Review
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $rate = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Constraints\Length(min: 1, max: 255)]
    private ?string $description = null;

    #[ORM\ManyToOne(inversedBy: 'reviews')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Deck $deck = null;

    #[ORM\ManyToOne(inversedBy: 'reviews')]
    #[ORM\JoinColumn(nullable: false)]
    private ?AppUser $reviewed_by = null;

    // Return identifier
    public function getId(): ?int
    {
        return $this->id;
    }

    // Return score of review
    public function getRate(): ?int
    {
        return $this->rate;
    }

    // Sets score to review
    public function setRate(int $rate): static
    {
        $this->rate = $rate;

        return $this;
    }

    // Return description of review if exists
    public function getDescription(): ?string
    {
        return $this->description;
    }

    // Sets description to review
    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    // Return deck review belongs to
    public function getDeck(): ?Deck
    {
        return $this->deck;
    }

    // Sets deck review belongs to
    public function setDeck(?Deck $deck): static
    {
        $this->deck = $deck;

        return $this;
    }

    // Return person who reviewed
    public function getReviewedBy(): ?AppUser
    {
        return $this->reviewed_by;
    }

    // Sets person who reviewed
    public function setReviewedBy(?AppUser $reviewed_by): static
    {
        $this->reviewed_by = $reviewed_by;

        return $this;
    }
}

project/impl/src/Form/DeckType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Deck;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class DeckType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                    'label' => 'Nazev',
                    'required' => true,
                ]
            )
            ->add('about', TextareaType::class, [
                    'label' => 'Popis',
                    'required' => false,
                ]
            )
            ->add('categories', EntityType::class, [
                'class' => Category::class,
                'label' => 'Přidat kategorii',
                'required' => false,
                'choice_label' => 'name',
                'multiple' => true,
                'expanded' => true,
            ])
            ->add('new_category', TextType::class, [
                'mapped' => false,
                'required' => false,
                'label' => 'Přidat novou kategorii',
            ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Deck::class,
        ]);
    }
}

project/impl/src/Controller/Api/DeckController.php
<?php
declare(strict_types=1);

/* This file contains code adapted from the Symfony documentation:
   - Serializer component://symfony.com/doc/current/serializer/.html#deserializing-an-object
   - Validator component: https://symfony.com/doc/current/validation.html
   Used for deserializing JSON data into an object and validating it.
*/

namespace App\Controller\Api;

use App\Entity\AppUser;
use App\Entity\Deck;
use App\Factory\DeckFactory;
use App\Service\DeckService;
use App\Service\ReviewService;
use App\Repository\CardRepository;
use App\Repository\DeckRepository;
use App\Resource\CollectionResource;
use App\Resource\DeckDetailResource;
use App\Resource\ReviewResource;
use App\Voter\DeckVoter;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\Validator\Validator\ValidatorInterface;

#[Route(path: '/api/decks')]
#[IsGranted('IS_AUTHENTICATED_FULLY')]
class DeckController extends AbstractController
{
    public function __construct(
        private DeckService     $deckService,
        private DeckFactory     $deckFactory,
        private DeckRepository  $deckRepository,
        private CardRepository  $cardRepository,
        private ReviewService $reviewService
    ){}

    /* Returns a JSON response with the user's personal decks for regular users,
       or all collections for admins. */
    #[Route(path: '', name: 'api_all_decks', methods: ['GET'])]
    public function all_decks(Request $request): Response{
        /** @var AppUser $user */
        $user = $this->getUser();
        $decks = $this->deckRepository->findByUser($user);
        return $this->json(new CollectionResource(
            _self: $this->generateUrl('api_all_decks'),
            data: array_map(
                fn (Deck $deck) => $this->deckFactory->list($deck),
                $decks
            ),
        ));
    }

    // Returns a JSON response with details of a specific deck.
    #[Route(path: '/deck/{id}', name: 'api_deck', requirements: ['id' => '\d+'], methods: ['GET'])]
    public function show_deck(Deck $deck): Response
    {
        if (!$this->isGranted(DeckVoter::VIEW, $deck)){
            throw $this->createAccessDeniedException();
        }
        return $this->json($this->deckFactory->show($deck));
    }

    /* Handles creating a new deck or updating an existing one.
       If editing an existing deck, checks if the user has permission to edit it.
       Deserializes the request content into a DeckDetailResource object, validates the deck,
       and stores it. Returns the details of the created or updated deck in a JSON response. */
    #[Route(path: '/my_decks', name: 'api_deck_create', methods: ['POST'])]
    #[Route(path: '/my_decks/{id}', name: 'api_deck_edit', requirements: ['id' => '\d+'], methods: ['PUT'])]
    public function create(?Deck $deck, Request $request,
                           SerializerInterface $serializer, ValidatorInterface $validator): Response{
        if ($deck && !$this->isGranted(DeckVoter::EDIT_REMOVE, $deck)){
            throw $this->createAccessDeniedException();
        }
        /** @var AppUser $user */
        $user = $this->getUser();
        $resource = $serializer->deserialize(
            $request->getContent(),
            DeckDetailResource::class,
            'json'
        );
        if (! $deck){
            $deck = new Deck();
        }
        $this->deckFactory->create($resource, $deck, $user);
        $violations = $validator->validate($deck);
        if (count($violations) > 0) {
            return $this->json((string) $violations, 400);
        }
        $this->deckService->store($deck);
        return $this->json($this->deckFactory->show($deck));
    }

    /* Handles the duplication of a deck.
       Creates a new deck based on the existing one and
       returns the details of the newly created deck in a JSON response.*/
    #[Route(path: '/deck/{id}', name: 'api_deck_clone', requirements: ['id' => '\d+'], methods: ['POST'])]
    public function duplicate(Deck $deck): Response{
        if (!$this->isGranted(DeckVoter::VIEW, $deck)){
            throw $this->createAccessDeniedException();
        }
        /** @var AppUser $user */
        $user = $this->getUser();
        $new_deck = $this->deckService->clone($deck, $user);
        return $this->json($this->deckFactory->show($new_deck));
    }

    // Handles the removing of a deck. Checks if the user has permission to remove it.
    #[Route(path: '/my_decks/{id}', name: 'api_deck_remove', requirements: ['id' => '\d+'], methods: ['DELETE'])]
    public function remove(Deck $deck): Response{
        if (!$this->isGranted(DeckVoter::EDIT_REMOVE, $deck)){
            throw $this->createAccessDeniedException();
        }
        $this->deckService->remove($deck);
        return $this->json(['message' => 'Odstraneno'], 200);
    }

    // Handles the publishing of a deck. Checks if the user has permission to publish it.
    #[Route(path: '/my_decks/deck/{id}', name: 'api_deck_publicate', requirements: ['id' => '\d+'], methods: ['POST'])]
    public function publicate(Deck $deck): Response{
        if (!$this->isGranted(DeckVoter::EDIT_REMOVE, $deck)){
            throw $this->createAccessDeniedException();
        }
        if ($deck->getParent()){
            throw new \LogicException('Tato kolekce je kopií již existující');
        }
        if (!$deck->isPrivate()){
            throw new \LogicException('Tato kolekce již byla zveřejněna');
        }
        $this->deckService->publicate($deck);
        return $this->json(['message' => 'Publikovano'], 200);
    }

    /* Handles submitting a review for a deck.
       Ensures the user has permission to review it.
       Deserializes the request content into a ReviewResource object, validates the review,
       and stores it. Returns the updated deck details in a JSON response. */
    #[Route(path: '/deck/{id}/review', name: 'api_deck_review', requirements: ['id' => '\d+'], methods: ['POST'])]
    public function add_review(Deck $deck, Request $request,
                               SerializerInterface $serializer, ValidatorInterface $validator): Response{
        if (!$this->isGranted(DeckVoter::STUDY_TEST, $deck))
            throw $this->createAccessDeniedException();
        if ($this->cardRepository->countOfStudied($deck) !== $deck->getCards()->count())
            throw new \LogicException('Nemůžete hodnotit kolekci, dokud neprojdete všechny její kartičky.');
        /** @var AppUser $user */
        $user = $this->getUser();
        $resource = $serializer->deserialize(
            $request->getContent(),
            ReviewResource::class,
            'json'
        );
        $review = $this->deckFactory->add_review($resource, $deck, $user);
        $violations = $validator->validate($review);
        if (count($violations) > 0) {
            return $this->json((string) $violations, 400);
        }
        $this->reviewService->store($review, $deck, $user);
        return $this->json($this->deckFactory->show($deck));
    }
}

project/impl/templates/decks/accept.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="{{ asset('/styles/form.css') }}">
{% endblock %}

{% block header %}
    <div class="head">
        <h1>{{ title }}</h1>
        <p><a href="{{ path('my_decks') }}">Zpet</a></p>
    </div>
{% endblock %}

{% block content %}
    <section class="form">
        <p>Skutečně si přejete {{ akce }} kolekci <strong>{{ deck.name }}</strong>?</p>
        {{ form(form) }}
    </section>
{% endblock %}

project/impl/templates/decks/deck.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="{{ asset('/styles/deck.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('/styles/modal.css') }}">
{% endblock %}

{% block scripts %}
    <script type="module" src="{{ asset('/scripts/modalInicialize.js') }}" defer></script>
{% endblock %}

{% block content %}
    <section class="menu">
            <a href="{{ path('decks') }}">Kolekce</a>
            <a href="{{ path('my_decks') }}">Moje kolekce</a>
            {% if deck.isPrivate %}
            <a href="{{ path('deck_tests', {id: deck.id}) }}">Testy</a>
            {% endif %}
            <a href="{{ path('stats') }}">Statistiky</a>
            <a href="{{ path('goals') }}">Moje cíle</a>
            <a href="{{ path('app_user') }}">Nastaveni</a>
            <div class="bottom_links">
                <a href="{{ path('notifications') }}" title="Notifikace"
                   {% if unread_notifications > 0 %}class="unread"{% endif %}>
                    <i class="fa-solid fa-bell"></i>
                </a>
                <a href="{{ path('logout') }}" title="Odhlásit se"><i class="fa-solid fa-right-from-bracket"></i></a>
            </div>
    </section>
    <section class="deck">
        <div class="deck_info">
            <h2>{{ deck.name }}</h2>
            {% if not deck.isPrivate or deck.owner is not same as(app.user) %}
                <a id="openModal"
                   data-value="duplicate_collection"
                   data-collection="{{ deck.name }}"
                   href="{{ path('deck_clone', {id: deck.id}) }}"
                   data-url="{{ path('api_deck_clone', {id: deck.id}) }}">Duplikovat</a>
                <p>Vytvořil: {{ deck.owner.login }}</p>
            {% else %}
            <p>Kartiček k nauceni: {{ deck.countOfCardsToStudy }}</p>
            <a href="{{ path('study', {id: deck.id}) }}">Studovat</a>
            {% endif %}
        </div>
        <div class="deck_edit">
            {% if deck.isPrivate and
                deck.owner is same as app.user and
                deck.countOfStudiedCards == deck.cards|length
            %}
                <a id="openModal"
                   data-value="deck_review"
                   data-url="{{ path('api_deck_review', {id: deck.id}) }}"
                   href="{{ path('deck_review', {id: deck.id}) }}"
                   title="Zanechat recenzi"><i class="fa-solid fa-comment-dots"></i></a>
            {% endif %}
            {% if deck.isPrivate and deck.owner is same as(app.user) %}
                <a id="openModal"
                   data-value="duplicate_collection"
                   data-collection="{{ deck.name }}"
                   href="{{ path('deck_clone', {id: deck.id}) }}"
                   data-url="{{ path('api_deck_clone', {id: deck.id}) }}"
                   title="Duplikovat"><i class="fa-solid fa-clone"></i></a>
            {% endif %}
            {% if deck.isPrivate and not deck.getParent and deck.cards|length > 0 %}
                <a id="openModal"
                   data-value="publicate_collection"
                   data-collection="{{ deck.name }}"
                   href="{{ path('deck_publicate', {id: deck.id}) }}"
                   data-url="{{ path('api_deck_publicate', {id: deck.id}) }}"
                   title="Publikovat"><i class="fa-solid fa-unlock"></i></a>
            {% endif %}
            {% if is_granted('ROLE_ADMIN') %}
                <a id="openModal"
                   data-value="edit_collection"
                   data-url="{{ path('api_deck_edit', {id: deck.id}) }}"
                   href="{{ path('deck_edit', {id: deck.id}) }}"
                   title="Upravit"><i class="fa-solid fa-pen"></i></a>
                <a id="openModal"
                   data-value="remove_collection"
                   data-collection="{{ deck ? deck.name : null }}"
                   data-url="{{ path('api_deck_remove', {id: deck.id}) }}"
                   href="{{ path('deck_remove', {id: deck.id}) }}"
                   title="Odstarnit"><i class="fa-solid fa-trash"></i></a>
            {% endif %}
        </div>
        {% if not deck.isPrivate and deck.reviews is not empty%}
                <div class="reviews">
                    {% for review in deck.reviews %}
                        <div class="review">
                            <div class="review_head">
                                <p>{{ review.reviewedBy.login }}</p>
                                <div class="stars">
                                    {% for i in 1..5 %}
                                        {% if i <= review.rate %}
                                            <i class="fa-solid fa-star" style="color: gold;"></i>
                                        {% else %}
                                            <i class="fa-regular fa-star" style="color: #ccc;"></i>
                                        {% endif %}
                                    {% endfor %}
                                </div>
                            </div>
                            {% if review.description %}
                                <p>{{ review.description }}</p>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
        {% endif %}
        {% if deck.about %}
            <p>O kolekci: {{ deck.about }}</p>
        {% endif %}
        <div class="cards_head">
            <p>Kartiček v kolekci: {{ deck.cards|length }}</p>
            {% if deck.isPrivate or is_granted('ROLE_ADMIN')%}
            <a id="openCardModal"
               data-value="card_create"
               data-url="{{ path('api_card_create', {id_deck: deck.id}) }}"
               href="{{ path('card_create', {id_deck: deck.id}) }}"
                title="Přidat kartičku"><i class="fa-solid fa-plus"></i></a>
            {% endif %}
        </div>
        <div class="cards">
            {% for card in deck.cards %}
                <div class="card">
                    <div class="front">
                        {% if card.frontImage %}
                            <img src="{{ asset('uploads/img/' ~ card.frontImage) }}" alt="">
                        {% endif %}
                        <p>{{ card.frontSide }}</p>
                    </div>
                    <p class="back">{{ card.backSide }}</p>
                    <a id="openModal"
                       data-value="show_card"
                       data-url="{{ path('api_card', {id_deck: deck.id, id_card: card.id}) }}"
                       href="{{ path('card', {id_deck: deck.id, id_card: card.id}) }}"
                       data-control="{{ edit_collection }}"
                    ></a>
                </div>
            {% endfor %}
        </div>
    </section>
    <dialog id="dialog">
    </dialog>
    <dialog id="card_dialog">
    </dialog>
{% endblock %}

project/impl/templates/decks/decks.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="{{ asset('/styles/decks.css') }}">
{% endblock %}

{% block content %}
    <div class="head">
        <h2>Všechny kolekce</h2>
        <div class="navigation">
            <a href="{{ path('my_decks') }}">Moje kolekce</a>
            <a href="{{ path('logout') }}" title="Odhlásit se"><i class="fa-solid fa-right-from-bracket"></i></a>
        </div>

    </div>
    <section class="filter">
        {{ form_start(filter) }}
        {{ form_rest(filter) }}
        {{ form_errors(filter) }}
        <button type="submit">Vyhledat</button>
        {{ form_end(filter) }}
    </section>
    {% if decks is not empty %}
        <div class="decks">
        {% for deck in decks %}
            <div class="deck">
                <h3>{{ deck.name }}</h3>
                <p> Hodnocení:
                    {% set totalScore = 0 %}
                    {% for review in deck.reviews %}
                        {% set totalScore = totalScore + review.rate %}
                    {% endfor %}
                    {% if deck.reviews|length > 0 %}
                        {{ (totalScore / deck.reviews|length)|number_format(1, '.', '') }}/5
                    {% else %}
                        0/5
                    {% endif %}
                </p>
                {% if is_granted('ROLE_ADMIN') %}
                    <p>Patří: {{ deck.owner.login }}</p>
                    <p>{% if deck.isPrivate %} Privátní
                        {% else %} Veřejná
                        {% endif %}</p>
                {% endif %}
                <div class="deck_categories">
                    {% for category in deck.categories %}
                        <p class="deck_category">{{ category.name }}</p>
                    {% endfor %}
                </div>
                <a href="{{ path('deck', {id: deck.id}) }}"></a>
            </div>
            {% endfor %}
        </div>
    {% else %}
        <p>Žádná kolekce nebyla nalezena</p>
    {% endif %}
{% endblock %}

project/impl/templates/decks/form.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="{{ asset('/styles/form.css') }}">
{% endblock %}

{% block header %}
    <div class="head">
        <h1>{{ title }}</h1>
        <p><a href="{{ path('my_decks') }}">Zpět</a></p>
    </div>
{% endblock %}

{% block content %}
    <section class="form">
        {{ form_start(form) }}
        <div>
            <fieldset role="group">
                    {{ form_label(form.name) }}
                    {{ form_widget(form.name) }}
                    {{ form_errors(form.name) }}
            </fieldset>
            <fieldset role="group">
                    {{ form_label(form.about) }}
                    {{ form_widget(form.about) }}
                    {{ form_errors(form.about) }}
            </fieldset>
        </div>
        <div class="categories">
                <p>Kategorie</p>
                <div class="categories_choice">
                    {% for child in form.categories %}
                        <div class="checkbox-wrapper">
                            {{ form_widget(child, { attr: { class: 'custom_checkbox' } }) }}
                            {{ form_label(child, null, { label_attr: { class: 'custom_label' } }) }}
                            {{ form_errors(child) }}
                        </div>
                    {% endfor %}
                </div>
        </div>
        {{ form_errors(form) }}
        {{ form_rest(form) }}
        <button type="submit">{{ deck ? 'Upravit' : 'Vytvořit' }}</button>
        {{ form_end(form) }}
    </section>
{% endblock %}

project/impl/templates/decks/review.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="{{ asset('/styles/form.css') }}">
{% endblock %}

{% block header %}
    <div class="head">
        <h1>Zanechat recenzi</h1>
        <p><a href="{{ path('deck', {id: deck.id}) }}">Zpět</a></p>
    </div>
{% endblock %}

{% block content %}
    <section class="form">
        {{ form_start(form) }}
        <div>
            <label class="required">Hodnocení kolekce</label>
            <div class="rating">
                {% for child in form.rate %}
                    {{ form_widget(child) }}
                    <label for="{{ child.vars.id }}"><i class="fa-solid fa-star"></i></label>
                {% endfor %}
            </div>
        </div>
        {{ form_errors(form) }}
        {{ form_rest(form) }}
        <button type="submit">Potvrdit</button>
        {{ form_end(form) }}
    </section>
{% endblock %}

project/impl/templates/decks/user_decks.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="{{ asset('/styles/user_decks.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('/styles/modal.css') }}">
{% endblock %}

{% block scripts %}
    <script type="module" src="{{ asset('/scripts/modalInicialize.js') }}" defer></script>
{% endblock %}

{% block content %}
    <section class="menu">
        <a href="{{ path('decks') }}">Kolekce</a>
        <a href="{{ path('stats') }}">Statistiky</a>
        <a href="{{ path('goals') }}">Moje cíle</a>
        <a href="{{ path('app_user') }}">Nastaveni</a>
        <div class="bottom_links">
            <a href="{{ path('notifications') }}" title="Notifikace"
               {% if unread_notifications > 0 %}class="unread"{% endif %}>
                <i class="fa-solid fa-bell"></i>
            </a>
            <a href="{{ path('logout') }}" title="Odhlásit se"><i class="fa-solid fa-right-from-bracket"></i></a>
        </div>

    </section>
    <section class="my_decks">
        <div class="head">
            <h2>Moje kolekce</h2>
            <p><a id="openModal"
                  data-value="create_collection"
                  data-url="{{ path('api_deck_create') }}"
                  href="{{ path('deck_create') }}">Vytvořit novou kolekci</a></p>
        </div>
        {% if decks is not empty %}
            <div class="decks">
            {% for deck in decks %}
                <div class="deck">
                    <h3>{{ deck.Name }}</h3>
                    <div class="deck_info">
                        <p>Karticek v kolekci: {{ deck.cards|length }}</p>
                        <div class="progress_container" title="Počet naučených kartiček">
                            {% if deck.cards|length > 0 %}
                                {% set width = (deck.countOfStudiedCards / deck.cards|length) * 100 %}
                            {% else %}
                                {% set width = 0 %}
                            {% endif %}
                            <div class="progress_bar"
                                 style="width:{{ width }}%;">
                            </div>
                        </div>
                        <div class="deck_edit">
                            <a id="openModal"
                               data-value="edit_collection"
                               data-url="{{ path('api_deck_edit', {id: deck.id}) }}"
                               href="{{ path('deck_edit', {id: deck.id}) }}"
                               title="Upravit"><i class="fa-solid fa-pen"></i></a>
                            <a id="openModal"
                               data-value="remove_collection"
                               data-collection="{{ deck ? deck.name : null }}"
                               data-url="{{ path('api_deck_remove', {id: deck.id}) }}"
                               href="{{ path('deck_remove', {id: deck.id}) }}"
                               title="Odstarnit"><i class="fa-solid fa-trash"></i></a>
                            <a href="{{ path('deck', {id:deck.id}) }}"
                               title="Prostudovat"><i class="fa-solid fa-play"></i></a>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
        {% else %}
            <p>Žádná kolekce nebyla nalezena</p>
        {% endif %}
    </section>
    <dialog id="dialog"></dialog>
{% endblock %}