project/impl/src/Entity/Card.php
<?php

namespace App\Entity;

use App\Repository\CardRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CardRepository::class)]
class Card
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $front_side = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $back_side = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $to_learn = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $last_learned = null;

    #[ORM\Column(nullable: true)]
    private ?int $learn_score = null;

    #[ORM\ManyToOne(inversedBy: 'cards')]
    private ?Deck $deck = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $front_image = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $back_image = null;

    #[ORM\OneToMany(targetEntity: TestResult::class, mappedBy: 'card')]
    private Collection $testResults;

    public function __construct()
    {
        $this->testResults = new ArrayCollection();
    }

    // Return identifier
    public function getId(): ?int
    {
        return $this->id;
    }

    // Return text from the front side of card
    public function getFrontSide(): string
    {
        return $this->front_side;
    }

    // Sets text to front side of card
    public function setFrontSide(string $front_side): static
    {
        $this->front_side = $front_side;

        return $this;
    }

    // Return text from the back side of card
    public function getBackSide(): string
    {
        return $this->back_side;
    }

    // Sets text to back side of card
    public function setBackSide(string $back_side): static
    {
        $this->back_side = $back_side;

        return $this;
    }

    // Return time when card must be learned
    public function getToLearn(): ?\DateTimeInterface
    {
        return $this->to_learn;
    }

    // Sets time when card must be learned
    public function setToLearn(?\DateTimeInterface $to_learn): static
    {
        $this->to_learn = $to_learn;

        return $this;
    }

    // Return time when card was learned for the last time
    public function getLastLearned(): ?\DateTimeImmutable
    {
        return $this->last_learned;
    }

    // Sets time when card was learned for the last time
    public function setLastLearned(?\DateTimeImmutable $last_learned): void
    {
        $this->last_learned = $last_learned;
    }

    // Return score for last learning of card
    public function getLearnScore(): ?int
    {
        return $this->learn_score;
    }

    // Sets score for last learning of card
    public function setLearnScore(?int $learn_score): static
    {
        $this->learn_score = $learn_score;

        return $this;
    }

    // Return deck that the card belongs to
    public function getDeck(): ?Deck
    {
        return $this->deck;
    }

    // Sets deck that the card belongs to
    public function setDeck(?Deck $deck): static
    {
        $this->deck = $deck;

        return $this;
    }

    // Get image on the front side of card if exists
    public function getFrontImage(): ?string
    {
        return $this->front_image;
    }

    // Sets image to the front side of card
    public function setFrontImage(?string $front_image): static
    {
        $this->front_image = $front_image;

        return $this;
    }

    // Get image on the back side of card if exists
    public function getBackImage(): ?string
    {
        return $this->back_image;
    }

    // Sets image to the back side of card
    public function setBackImage(?string $back_image): static
    {
        $this->back_image = $back_image;

        return $this;
    }

    // Return questions that are associated with card
    /**
     * @return Collection<int, TestResult>
     */
    public function getTestResults(): Collection
    {
        return $this->testResults;
    }

    // Add question that is associated with card
    public function addTestResult(TestResult $testResult): static
    {
        if (!$this->testResults->contains($testResult)) {
            $this->testResults->add($testResult);
            $testResult->setCard($this);
        }

        return $this;
    }

    // Remove question associated with card
    public function removeTestResult(TestResult $testResult): static
    {
        if ($this->testResults->removeElement($testResult)) {
            if ($testResult->getCard() === $this) {
                $testResult->setCard(null);
            }
        }

        return $this;
    }

    // Checks if card can be studied now
    public function canStudyNow(): bool{
        if ($this->last_learned){
            return $this->to_learn <= new \DateTimeImmutable();
        }
        return true;
    }
}

project/impl/src/Form/CardType.php
<?php

namespace App\Form;

use App\Entity\Card;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CardType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $card = $options['data'];
        $builder
            ->add('front_image', FileType::class, [
                'mapped' => false,
                'required' => false,
                'attr' => [
                    'accept' => 'image/jpeg, image/png, image/gif, image/jpg'
                ],
                'constraints' => [
                    new File([
                        'maxSize' => '2M',
                        'mimeTypes' => ['image/jpeg', 'image/png', 'image/gif', 'image/jpg'],
                        'mimeTypesMessage' => 'Nahrajte obrázek (JPEG, JPG, PNG, GIF)',
                    ])
                ]
            ])
            ->add('front_side', TextareaType::class, [
                'label' => 'Přední strana',
                'required' => true,
            ])
            ->add('back_image', FileType::class, [
                'mapped' => false,
                'required' => false,
                'attr' => [
                    'accept' => 'image/jpeg, image/png, image/gif, image/jpg'
                ],
                'constraints' => [
                    new File([
                        'maxSize' => '2M',
                        'mimeTypes' => ['image/jpeg', 'image/png', 'image/gif', 'image/jpg'],
                        'mimeTypesMessage' => 'Nahrajte obrázek (JPEG, JPG, PNG, GIF)',
                    ])
                ]
            ])
            ->add('back_side',TextareaType::class, [
                'label' => 'Zadní strana',
                'required' => true,
            ]);
        if ($card && $card->getFrontImage()){
            $builder->add('remove_front_image', CheckboxType::class, [
                'label' => 'Smazat aktuální obrázek?',
                'required' => false,
                'mapped' => false,
            ]);
        }
        if ($card && $card->getBackImage()){
            $builder->add('remove_back_image', CheckboxType::class, [
                'label' => 'Smazat aktuální obrázek?',
                'required' => false,
                'mapped' => false,
            ]);
        }
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Card::class,
        ]);
    }
}

project/impl/src/Controller/Api/CardController.php
<?php
declare(strict_types=1);

/* This file contains code adapted from the Symfony documentation:
   - Serializer component://symfony.com/doc/current/serializer/.html#deserializing-an-object
   - Validator component: https://symfony.com/doc/current/validation.html
   Used for deserializing JSON data into an object and validating it.
*/

namespace App\Controller\Api;

use App\Entity\Card;
use App\Entity\Deck;
use App\Factory\CardFactory;
use App\Service\CardService;
use App\Repository\DeckRepository;
use App\Resource\CardDetailResource;
use App\Resource\CollectionResource;
use App\Resource\DeckChoiceResource;
use App\Voter\DeckVoter;
use Symfony\Bridge\Doctrine\Attribute\MapEntity;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\Validator\Validator\ValidatorInterface;

#[Route(path: '/api/decks/deck')]
#[IsGranted('IS_AUTHENTICATED_FULLY')]
class CardController extends AbstractController
{
    public function __construct(
        private CardFactory         $cardFactory,
        private DeckRepository      $deckRepository,
        private CardService         $cardService,
        private SerializerInterface $serializer,
        private ValidatorInterface  $validator
    ){}

    // Returns a JSON response with details of a specific card.
    #[Route(path: '/{id_deck}/card/{id_card}', name: 'api_card', requirements: ['id_deck' => '\d+', 'id_card' => '\d+'], methods: ["GET"])]
    public function show_card(#[MapEntity(class: Deck::class, id: 'id_deck')]
                         Deck $deck,
                         #[MapEntity(class: Card::class, id: 'id_card')]
                         Card $card): Response{
        if (!$this->isGranted(DeckVoter::VIEW, $deck)){
            throw $this->createAccessDeniedException();
        }
        return $this->json($this->cardFactory->show($card));
    }

    // Returns a JSON response with all cards of the specific deck.
    #[Route(path: '/{id}/cards', name: 'api_deck_cards', methods: ['GET'])]
    public function deck_cards(Deck $deck, Request  $request): Response{
        if (!$this->isGranted(DeckVoter::VIEW, $deck)){
            throw $this->createAccessDeniedException();
        }
        return $this->json(new CollectionResource(
            _self: $this->generateUrl('api_deck', ['id' => $deck->getId()]),
            data: array_map(
                fn (Card $card) => $this->cardFactory->list($card),
                $deck->getCards()->toArray()
            ),
        ));
    }

    /* Handles creating a new card or editing an existing one.
       Ensures the user has permission to modify the deck.
       Deserializes the request content into a CardDetailResource object, validates the card,
       and stores it. Returns the details of the created or updated card in a JSON response. */
    #[Route(path: '/{id_deck}/card', name: 'api_card_create', requirements: ['id_deck' => '\d+'], methods: ['POST'])]
    #[Route(path: '/{id_deck}/card/{id_card}', name: 'api_card_edit', requirements: ['id_deck' => '\d+', 'id_card' => '\d+'], methods: ['PUT'])]
    public function create(#[MapEntity(class: Deck::class, id: 'id_deck')]
                           Deck $deck,
                           #[MapEntity(class: Card::class, id: 'id_card')]
                           ?Card $card, Request $request): Response{
        if (!$this->isGranted(DeckVoter::EDIT_REMOVE, $deck)){
            throw $this->createAccessDeniedException();
        }
        $resource = $this->serializer->deserialize(
            $request->getContent(),
            CardDetailResource::class,
            'json'
        );
        $card ??= new Card();
        $this->cardFactory->create($resource, $card);
        $violations = $this->validator->validate($card);
        if (count($violations) > 0) {
            return $this->json((string) $violations, 400);
        }
        $this->cardService->create($card, $deck);
        return $this->json($this->cardFactory->show($card));
    }

    /* Handles adding or updating front and/or back images for a specific card in a given deck.
       Ensures the user has permission to modify the deck. Accepts uploaded image files from the request,
       applies them to the card, and returns the updated card data as JSON. */
    #[Route(path: '/{id_deck}/card/{id_card}/image', name: 'api_card_image', requirements: ['id_deck' => '\d+', 'id_card' => '\d+'], methods: ['POST'])]
    public function addImage(#[MapEntity(class: Deck::class, id: 'id_deck')]
                             Deck $deck,
                             #[MapEntity(class: Card::class, id: 'id_card')]
                             Card $card, Request $request): Response{
        if (!$this->isGranted(DeckVoter::EDIT_REMOVE, $deck)){
            throw $this->createAccessDeniedException();
        }
        if ($request->files->get('front_image')){
            $front_image = $request->files->get('front_image');
            $this->cardService->setImage($card, $front_image, 'front');
        }
        if ($request->files->get('back_image')){
            $back_image = $request->files->get('back_image');
            $this->cardService->setImage($card, $back_image, 'back');
        }
        $this->cardService->store($card);
        return $this->json($this->cardFactory->show($card));
    }

    /* Handles copying a specific card to another deck.
       Deserializes the target deck ID from the request JSON body, finds the target deck,
       and clones the card into it. Returns a success message upon completion. */
    #[Route(path: '/{id_deck}/card/{id_card}', name: 'api_card_copy', requirements: ['id_deck' => '\d+', 'id_card' => '\d+'], methods: ["POST"])]
    public function clone(#[MapEntity(class: Deck::class, id: 'id_deck')]
                          Deck $deck,
                          #[MapEntity(class: Card::class, id: 'id_card')]
                          Card $card, Request $request): Response{
        if (!$this->isGranted(DeckVoter::VIEW, $deck)){
            throw $this->createAccessDeniedException();
        }
        $resource = $this->serializer->deserialize($request->getContent(),
            DeckChoiceResource::class,
            'json');
        $new_deck = $this->deckRepository->findOneById($resource->id);
        $this->cardService->clone($card, $new_deck);
        return $this->json(['message' => 'Zkopirovano'], 200);
    }

    // Handles the removing of a card. Ensures the user has permission to modify the deck.
    #[Route(path: '/{id_deck}/card/{id_card}', name: 'api_card_remove', requirements: ['id_deck' => '\d+', 'id_card' => '\d+'], methods: ["DELETE"])]
    public function remove(#[MapEntity(class: Deck::class, id: 'id_deck')]
                           Deck $deck,
                           #[MapEntity(class: Card::class, id: 'id_card')]
                           Card $card): Response{
        if (!$this->isGranted(DeckVoter::EDIT_REMOVE, $deck)){
            throw $this->createAccessDeniedException();
        }
        $this->cardService->remove($card);
        return $this->json(['message' => 'Odstraneno'], 200);
    }

    /* Handles the removal of the front image from a specific card.
       Checks if the user has permission to edit the deck. */
    #[Route(path: '/{id_deck}/card/{id_card}/front_image', name: 'api_card_remove_front_image', requirements: ['id_deck' => '\d+', 'id_card' => '\d+'], methods: ["DELETE"])]
    public function remove_front_image(#[MapEntity(class: Deck::class, id: 'id_deck')]
                           Deck $deck,
                           #[MapEntity(class: Card::class, id: 'id_card')]
                           Card $card): Response{
        if (!$this->isGranted(DeckVoter::EDIT_REMOVE, $deck)){
            throw $this->createAccessDeniedException();
        }
        $this->cardService->removeImage($card, 'front');
        $this->cardService->store($card);
        return $this->json(['message' => 'Odstraneno'], 200);
    }

    /* Handles the removal of the back image from a specific card.
       Checks if the user has permission to edit the deck. */
    #[Route(path: '/{id_deck}/card/{id_card}/back_image', name: 'api_card_remove_back_image', requirements: ['id_deck' => '\d+', 'id_card' => '\d+'], methods: ["DELETE"])]
    public function remove_back_image(#[MapEntity(class: Deck::class, id: 'id_deck')]
                                       Deck $deck,
                                       #[MapEntity(class: Card::class, id: 'id_card')]
                                       Card $card): Response{
        if (!$this->isGranted(DeckVoter::EDIT_REMOVE, $deck)){
            throw $this->createAccessDeniedException();
        }
        $this->cardService->removeImage($card, 'back');
        $this->cardService->store($card);
        return $this->json(['message' => 'Odstraneno'], 200);
    }
}

project/impl/templates/card/copy_card.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="{{ asset('/styles/form.css') }}">
{% endblock %}

{% block header %}
    <div class="head">
        <h1>{{ title }}</h1>
        <p><a href="{{ path('deck', {id: card.deck.id}) }}">Zpět</a></p>
    </div>
{% endblock %}

{% block content %}
    <section class="form">
        {{ form_start(form) }}
        <fieldset>
            <fieldset role="group">
                {{ form_label(form.deck_choice) }}
                {{ form_widget(form.deck_choice) }}
                {{ form_errors(form.deck_choice) }}
            </fieldset>
        </fieldset>
        {{ form_errors(form) }}
        {{ form_rest(form) }}
        <button type="submit">Zkopírovat</button>
        {{ form_end(form) }}
    </section>
{% endblock %}

project/impl/templates/card/form.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="{{ asset('/styles/form.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('/styles/card_form.css') }}">
{% endblock %}

{% block header %}
    <div class="head">
        <h1>{{ title }}</h1>
        {% if card.id %}
            <p><a href="{{ path('card', {id_deck: deck.id, id_card: card.id}) }}">Zpět</a></p>
        {% else %}
        <p><a href="{{ path('deck', {id: deck.id}) }}">Zpět</a></p>
        {% endif %}
    </div>
{% endblock %}

{% block content %}
    <section class="form">
        {{ form_start(form) }}
        <div>
                {{ form_label(form.front_side) }}
                {{ form_widget(form.front_side) }}
                {{ form_errors(form.front_side) }}
        </div>
        <div class="front_image">
            {% if card.frontImage %}
                <p>Změnit obrázek</p>
            {% else %}
                <p>Přidejte obrázek</p>
            {% endif %}
                {{ form_widget(form.front_image) }}
                {{ form_errors(form.front_image) }}
            {% if card.frontImage %}
                <div>
                    <img src="{{ asset('uploads/img/' ~ card.frontImage) }}" alt="">
                    <br>
                    {{ form_row(form.remove_front_image) }}
                </div>
            {% endif %}
        </div>
        <div>
                {{ form_label(form.back_side) }}
                {{ form_widget(form.back_side) }}
                {{ form_errors(form.back_side) }}
        </div>
        <div class="back_image">
            {% if card.backImage %}
                <p>Změnit obrázek</p>
            {% else %}
                <p>Přidejte obrázek</p>
            {% endif %}
            {{ form_widget(form.back_image) }}
            {{ form_errors(form.back_image) }}
            {% if card.backImage %}
                <div>
                    <img src="{{ asset('uploads/img/' ~ card.backImage) }}" alt="">
                    <br>
                    {{ form_row(form.remove_back_image) }}
                </div>
            {% endif %}
        </div>
        {{ form_errors(form) }}
        {{ form_rest(form) }}
        <button type="submit">{{ card ? 'Upravit' : 'Vytvořit' }}</button>
        {{ form_end(form) }}
    </section>
{% endblock %}

project/impl/templates/card/remove.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="{{ asset('/styles/form.css') }}">
{% endblock %}

{% block header %}
    <div class="head">
        <h1>{{ title }}</h1>
        <p><a href="{{ path('card', {id_deck: card.deck.id, id_card: card.id}) }}">Zpet</a></p>
    </div>
{% endblock %}

{% block content %}
    <section class="form">
        <p>Skutečně si přejete odstranit kartičku <strong>{{ card.frontSide }}</strong>?</p>
        {{ form(form) }}
    </section>
{% endblock %}

project/impl/templates/card/show.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="{{ asset('/styles/card.css') }}">
{% endblock %}

{% block content %}
    <div class="head">
        <h2>{{ card.deck.name }}</h2>
        <p><a href="{{ path('deck', {id: card.deck.id}) }}">Zpět</a></p>
    </div>
    <section class="card">
        <div class="card_edit">
            <a href="{{ path('card_copy', {id_deck: card.deck.id, id_card: card.id}) }}"><i class="fa-solid fa-share"></i></a>
            {% if is_granted('ROLE_ADMIN') or card.deck.owner is same as app.user  %}
            <a href="{{ path('card_edit', {id_deck: card.deck.id, id_card: card.id}) }}"><i class="fa-solid fa-pen"></i></a>
            <a href="{{ path('card_remove', {id_deck: card.deck.id, id_card: card.id}) }}"><i class="fa-solid fa-trash"></i></a>
            {% endif %}
        </div>
        <div class="cards_sides">
            <div class="front">
                {% if card.frontImage %}
                    <img src="{{ asset('uploads/img/' ~ card.frontImage) }}" alt="">
                {% endif %}
                <p>{{ card.frontSide }}</p>
            </div>
            <div class="back">
                {% if card.backImage %}
                    <img src="{{ asset('uploads/img/' ~ card.backImage) }}" alt="">
                {% endif %}
                <p>{{ card.backSide }}</p>
            </div>
        </div>
    </section>
{% endblock %}